keys:
  - &sam 2504791468b153b8a3963cc97ba53d1919c5dfd4
  - &masterace age12zlz6lvcdk6eqaewfylg35w0syh58sm7gh53q5vvn7hd7c6nngyseftjxl
creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
    - age:
      - *sam
      - *masterace
