return {
  -- {
  --       "Exafunction/codeium.nvim",
  --       event = "BufEnter",
  --       dependencies = {
  --         'nvim-lua/plenary.nvim',
  --         'MunifTanjim/nui.nvim',
  --         'rsh7th/nvim-cmp',
  --       },
  --       config = function()
  --         require("codeium").setup({
  --           bin_path = "/etc/profiles/per-user/sam/bin/codeium_language_server",
  --           tools = {
  --             language_server = "/etc/profiles/per-user/sam/bin/codeium_language_server"
  --           }
  --         })
  --       end
  --     },
  --     { -- override nvim-cmp plugin
  --       "hrsh7th/nvim-cmp",
  --       dependencies = {
  --         "Exafunction/codeium.nvim",
  --         event = "BufEnter",
  --         dependencies = {
  --           'nvim-lua/plenary.nvim',
  --           'MunifTanjim/nui.nvim',
  --           'rsh7th/nvim-cmp',
  --         },
  --         config = function()
  --           require("codeium").setup({
  --             wrapper = "/etc/profiles/per-user/sam/bin/codeium_language_server",
  --             tools = {
  --               language_server = "/etc/profiles/per-user/sam/bin/codeium_language_server"
  --             }
  --           })
  --         end
  --       },
  --       -- override the options table that is used in the `require("cmp").setup()` call
  --       opts = function(_, opts)
  --         -- opts parameter is the default options table
  --         -- the function is lazy loaded so cmp is able to be required
  --         local cmp = require "cmp"
  --         -- modify the sources part of the options table
  --         opts.sources = cmp.config.sources {
  --           { name = "nvim_lsp", priority = 1000 },
  --           { name = "luasnip", priority = 750 },
  --           { name = "buffer", priority = 500 },
  --           { name = "path", priority = 250 },
  --         }
  --
  --         -- return the new table to be used
  --         return opts
  --       end,
  --     },
}
