$term = foot
# $wlogout = ~/.config/hypr/scripts/wlogout
$app_launcher = ~/.config/hypr/scripts/menu
$volume = ~/.config/hypr/scripts/volume
$backlight = ~/.config/hypr/scripts/brightness
$lockscreen = ~/.config/hypr/scripts/lockscreen
$colorpicker = ~/.config/hypr/scripts/colorpicker
$files = nautilus
$browser = firefox

# -- App Launcher --
bind=SUPER,less,exec,$app_launcher
bind=SUPER,B,exec,$browser
bind=SUPER,E,exec,$files
bind=SUPER,T,exec,$term

# -- Hyprland --
bind=SUPER,Q,killactive,
bind=SUPERSHIFT,X,exec,exit,
bind=SUPER,F,fullscreen,
bind=SUPER,Space,togglefloating,
bind=SUPER,S,pseudo,

# -- Misc --
bind=SUPER,N,exec,nm-connection-editor  # need install network-manager-applet
bind=SUPER,P,exec,$colorpicker
bind=SUPER,L,exec,$lockscreen
# bind=CTRLALT,Delete,$wlogout

# -- Some nice mouse binds --
bindm=SUPER,mouse:272,movewindow
bindm=SUPER,mouse:273,resizewindow

# -- Function keys --
bind=,XF86MonBrightnessUp,exec,$backlight --inc
bind=,XF86MonBrightnessDown,exec,$backlight --dec
bind=,XF86AudioRaiseVolume,exec,$volume --inc
bind=,XF86AudioLowerVolume,exec,$volume --dec
bind=,XF86AudioMute,exec,$volume --toggle
bind=,XF86AudioMicMute,exec,$volume --toggle-mic
bind=,XF86AudioNext,exec,mpc next
bind=,XF86AudioPrev,exec,mpc prev
bind=,XF86AudioPlay,exec,mpc toggle
bind=,XF86AudioStop,exec,mpc stop

# -- Screenshots --
# bind=SUPER,P,exec,hyprshot -m output -o ~/Pictures/Screenshots -- imv
# bind=SUPERSHIFT,P,exec,hyprshot -m window -o ~/Pictures/Screenshots -- imv
# flameshot do not recognize hyprland as a wayland compositor, so we set it to sway here
bind=Control_L,F9,exec,grimblast copysave area
bind=Control_L,F8,exec,amixer set Capture toggle
