# You can put custom rules here
# Window/layer rules: https://wiki.hyprland.org/Configuring/Window-Rules/
# Workspace rules: https://wiki.hyprland.org/Configuring/Workspace-Rules/

windowrule = float, ^(foot)$
windowrule = float, ^(pavucontrol)$
windowrule = float, title:(Easy Effects)$
windowrule = float, title:(Picture-in-Picture)$
windowrule = float, title:^(Extension)(.*)$
