# ########################### Keybinds for Hyprland ############################
# Swap windows
bind = Super+Shift, left, movewindow, l
bind = Super+Shift, right, movewindow, r
bind = Super+Shift, up, movewindow, u
bind = Super+Shift, down, movewindow, d
bind = Super, P, pin
# Move focus
bind = Super, left, movefocus, l
bind = Super, right, movefocus, r
bind = Super, up, movefocus, u
bind = Super, down, movefocus, d
bind = Super, BracketLeft, movefocus, l
bind = Super, BracketRight, movefocus, r

# Workspace, window, tab switch with keyboard
bind = Control+Super, right, workspace, +1
bind = Control+Super, left, workspace, -1
bind = Super, mouse:275, workspace, -1
bind = Super, mouse:276, workspace, +1
bind = Control+Super, BracketLeft, workspace, -1
bind = Control+Super, BracketRight, workspace, +1
bind = Control+Super, up, workspace, -5
bind = Control+Super, down, workspace, +5
bind = Super, Page_Down, workspace, +1
bind = Super, Page_Up, workspace, -1
bind = Control+Super, Page_Down, workspace, +1
bind = Control+Super, Page_Up, workspace, -1
bind = Super+Alt, Page_Down, movetoworkspace, +1
bind = Super+Alt, Page_Up, movetoworkspace, -1
bind = Super+Shift, Page_Down, movetoworkspace, +1
bind = Super+Shift, Page_Up, movetoworkspace, -1
bind = Control+Super+Shift, Right, movetoworkspace, +1
bind = Control+Super+Shift, Left, movetoworkspace, -1
bind = Super+Shift, mouse_down, movetoworkspace, -1
bind = Super+Shift, mouse_up, movetoworkspace, +1
bind = Super+Alt, mouse_down, movetoworkspace, -1
bind = Super+Alt, mouse_up, movetoworkspace, +1

# Window split ratio
binde = Super, Minus, splitratio, -0.1
binde = Super, Equal, splitratio, 0.1
binde = Super, Semicolon, splitratio, -0.1
binde = Super, Apostrophe, splitratio, 0.1

# Fullscreen
bind = Super, F, fullscreen, 0
bind = Super, D, fullscreen, 1
bind = Super_Alt, F, fakefullscreen, 0

# Workspaces
bind=SUPER,ampersand,workspace,1
bind=SUPER,eacute,workspace,2
bind=SUPER,quotedbl,workspace,3
bind=SUPER,apostrophe,workspace,4
bind=SUPER,parentleft,workspace,5
bind=SUPER,minus,workspace,6
bind=SUPER,egrave,workspace,7
bind=SUPER,underscore,workspace,8
bind=SUPER,ccedilla,workspace,9
bind=SUPER,agrave,workspace,10

# Send to Workspaces
bind=SUPERSHIFT,ampersand,movetoworkspace,1
bind=SUPERSHIFT,eacute,movetoworkspace,2
bind=SUPERSHIFT,quotedbl,movetoworkspace,3
bind=SUPERSHIFT,apostrophe,movetoworkspace,4
bind=SUPERSHIFT,parentleft,movetoworkspace,5
bind=SUPERSHIFT,minus,movetoworkspace,6
bind=SUPERSHIFT,egrave,movetoworkspace,7
bind=SUPERSHIFT,underscore,movetoworkspace,8
bind=SUPERSHIFT,ccedilla,movetoworkspace,9

# Scroll through existing workspaces with (Control) + Super + scroll
bind = Super, mouse_up, workspace, +1
bind = Super, mouse_down, workspace, -1
bind = Control+Super, mouse_up, workspace, +1
bind = Control+Super, mouse_down, workspace, -1

# Move/resize windows with Super + LMB/RMB and dragging
bindm = Super, mouse:272, movewindow
bindm = Super, mouse:273, resizewindow
# bindm = Super, mouse:274, movewindow
bind = Control+Super, Backslash, resizeactive, exact 640 480
