#!/usr/bin/env bash

DIR=~/.config/wallpapers/gif/

echo $DIR

PICS=($(ls $DIR -I '*.json'))

#echo "$PICS"

RANDOMPICS=${PICS[ $RANDOM % ${#PICS[@]} ]}

swww query || swww init

echo Setting ${DIR}/${RANDOMPICS}

swww img ${DIR}/${RANDOMPICS} --transition-fps 30 --transition-type any --transition-duration 3
